### ISSUE TITLE
Audio Desync

### ISSUE THREAD

**Issue by Lep19** [NunoDasNeves/slp-to-mp4#14]
Hello,

It seems there's a delay in the video necessary for the playback emulator to load the stage that the audio playback doesn't account for. In other words, while the emulator is loading the stage, the audio plays as if the match had started as normal, so it remains ahead of the video for the rest of the recording. Is there a way to delay the audio recording a bit or to separate the audio and video recordings so that they can be assembled manually to work around this?

Thanks.

**Comment by NunoDasNeves** [comment]
Should be fixed in https://github.com/NunoDasNeves/slp-to-mp4/commit/2f05fb86ea28693dbaed053878dd39f30bb80b11
